### ISSUE TITLE
Please add a sample k6 test code

### ISSUE THREAD

**Issue by kpassoubady** [szkiba/xk6-dotenv#2]
Based on the readme, it is very hard to understand how to use the parse method. 
Can you please write a simple k6 example script and show with .env, .env.develop, env.test files how to use develop in one scenario and test in another scenario or run. Appreciated for your help.

**Comment by n1nj4z33** [comment]
import { parse } from "k6/x/dotenv";

const env = parse(open(".env.test"));

console.log(env.BASE_URL)
console.log(env.PUBLIC_KEY)
console.log(env.PRIVATE_KEY)

**Comment by kpassoubady** [comment]
Looks good.

**Comment by andreasciamanna** [comment]
So, is it required to call it that way, or, like `dotenv`, it can automatically load the `.env` file based on the conventions?

**Comment by MoKhajavi75** [comment]
Hey @kpassoubady and @szkiba 
Is there any way to load the `.env` file automatically?

**Comment by szkiba** [comment]
Yes, you should import k6/x/dotenv modult in your script.
