### ISSUE TITLE
Received an "ERRO[0000] unknown module: k6/x/dotenv" after installing xk6-dotenv

### ISSUE THREAD

**Issue by jmosley5** [szkiba/xk6-dotenv#3]
After following the instructions for installation, I'm receiving the following error:
<img width="421" alt="Screen Shot 2021-12-23 at 11 35 06 AM" src="https://user-images.githubusercontent.com/12145163/147268616-58f0b843-bbba-46b1-a2fc-999472da7a09.png">

What am I missing?

Here's my code:
```
import { parse } from 'k6/x/dotenv'

const user_email = parse(EMAIL)
const user_password = parse(PASSWORD)

**Comment by stevenmchaves** [comment]
I needed to do the following on Linux. I didn't have go installed so here were the steps that I used:
wget https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
 tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
 go version
 go install go.k6.io/xk6/cmd/xk6@latest
 xk6 build --with github.com/szkiba/xk6-dotenv@latest

**Comment by PaulMEdwards** [comment]
Is it the case that the only way to use the xk6 dotenv module is to build your own k6 binary?

**Comment by muratkeremozcan** [comment]
@szkiba can we get some documentation please?

I could not find a working repository or code sample, almost looks like tribal knowledge people know ...

I posted it also in the forums.
The goal is to use dotenv package and a .env file to store environment variables.

Naively, I expect this to be as simple as


```js
import * as dotenv from "k6/x/dotenv";

export default function (token) {

    console.log("the env var is ", dotenv.get("TEST_VAR"));
}
```


But not so. You get a "uknown module" error. Paul mentioned "building the custom binary with xk6" , what does this mean?

Looking above, it means:
```bash
wget https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go version
go install go.k6.io/xk6/cmd/xk6@latest
xk6 build --with github.com/szkiba/xk6-dotenv@latest
```

We want this to be as simple as someone pulls the repo, installs, gets the .env file, and things work.  We want to define the env vars in a repo, and for the CI to run as it would locally. My guess is the same instructions in CI. Please confirm.



https://community.k6.io/t/k6-dotenv-support/1815/6

**Comment by muratkeremozcan** [comment]
Here's a painless solution to environment variables with k6; just use dotenv-cli.

Demo:
https://www.youtube.com/watch?v=22OmBFKj7fc

**Comment by szkiba** [comment]
@muratkeremozcan your solution is perfect if you fine with external executable dependency and not want to build custom k6. Thats fine, so this extension is not for you. I got your point, and agree, it would be fine a web based custom k6 builder (similar o caddy web server)

**Comment by szkiba** [comment]
not related to this specific extension
