### ISSUE TITLE
WARN[0001] Module 'k6/x/dotenv' is using deprecated APIs that will be removed in k6 v0.38.0

### ISSUE THREAD

**Issue by stevenmchaves** [szkiba/xk6-dotenv#4]
Seeing this warning:
WARN[0001] Module 'k6/x/dotenv' is using deprecated APIs that will be removed in k6 v0.38.0, for more details on how to update it see https://k6.io/docs/extensions/guides/create-an-extension/#advanced-javascript-extension

**Comment by szkiba** [comment]
It should be ok now, thanx to @qapquiz 's PR. @stevenmchaves may I ask you to close...
